*** Reading local file: /usr/local/airflow/logs/my_operator_tester_dag/file_sensor/2019-11-17T12:00:00+00:00/1.log
[2019-11-18 22:27:32,364] {{taskinstance.py:616}} INFO - Dependencies all met for <TaskInstance: my_operator_tester_dag.file_sensor 2019-11-17T12:00:00+00:00 [queued]>
[2019-11-18 22:27:32,385] {{taskinstance.py:616}} INFO - Dependencies all met for <TaskInstance: my_operator_tester_dag.file_sensor 2019-11-17T12:00:00+00:00 [queued]>
[2019-11-18 22:27:32,385] {{taskinstance.py:834}} INFO - 
--------------------------------------------------------------------------------
[2019-11-18 22:27:32,385] {{taskinstance.py:835}} INFO - Starting attempt 1 of 1
[2019-11-18 22:27:32,386] {{taskinstance.py:836}} INFO - 
--------------------------------------------------------------------------------
[2019-11-18 22:27:32,459] {{taskinstance.py:855}} INFO - Executing <Task(FileSensor): file_sensor> on 2019-11-17T12:00:00+00:00
[2019-11-18 22:27:32,459] {{base_task_runner.py:133}} INFO - Running: ['airflow', 'run', 'my_operator_tester_dag', 'file_sensor', '2019-11-17T12:00:00+00:00', '--job_id', '38', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/sensor.py', '--cfg_path', '/tmp/tmpjqt1z455']
[2019-11-18 22:27:33,905] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor [2019-11-18 22:27:33,904] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1925
[2019-11-18 22:27:33,961] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-18 22:27:33,961] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   """)
[2019-11-18 22:27:34,263] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor [2019-11-18 22:27:34,261] {{__init__.py:51}} INFO - Using executor LocalExecutor
[2019-11-18 22:27:35,080] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor [2019-11-18 22:27:35,080] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/sensor.py
[2019-11-18 22:27:35,200] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor [2019-11-18 22:27:35,199] {{cli.py:516}} INFO - Running <TaskInstance: my_operator_tester_dag.file_sensor 2019-11-17T12:00:00+00:00 [running]> on host a56db5abb97b
[2019-11-18 22:27:35,277] {{taskinstance.py:1047}} ERROR - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base_sensor_operator.py", line 107, in execute
    while not self.poke(context):
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/sensors/file_sensor.py", line 57, in poke
    hook = FSHook(self.fs_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/fs_hook.py", line 39, in __init__
    self.basepath = conn.extra_dejson.get('path', '')
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 292, in extra_dejson
    if self.extra:
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 353, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 177, in get_extra
    return fernet.decrypt(bytes(self._extra, 'utf-8')).decode()
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 171, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
[2019-11-18 22:27:35,281] {{taskinstance.py:1078}} INFO - Marking task as FAILED.
[2019-11-18 22:27:35,318] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor Traceback (most recent call last):
[2019-11-18 22:27:35,318] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/bin/airflow", line 32, in <module>
[2019-11-18 22:27:35,318] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     args.func(args)
[2019-11-18 22:27:35,319] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-18 22:27:35,319] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     return f(*args, **kwargs)
[2019-11-18 22:27:35,319] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-18 22:27:35,319] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     _run(args, dag, ti)
[2019-11-18 22:27:35,319] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-18 22:27:35,319] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     pool=args.pool,
[2019-11-18 22:27:35,320] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-18 22:27:35,320] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     return func(*args, **kwargs)
[2019-11-18 22:27:35,320] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
[2019-11-18 22:27:35,320] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     result = task_copy.execute(context=context)
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base_sensor_operator.py", line 107, in execute
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     while not self.poke(context):
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/sensors/file_sensor.py", line 57, in poke
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     hook = FSHook(self.fs_conn_id)
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/fs_hook.py", line 39, in __init__
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     self.basepath = conn.extra_dejson.get('path', '')
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 292, in extra_dejson
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     if self.extra:
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 353, in __get__
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     retval = self.descriptor.__get__(instance, owner)
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 177, in get_extra
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     return fernet.decrypt(bytes(self._extra, 'utf-8')).decode()
[2019-11-18 22:27:35,321] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor   File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 171, in decrypt
[2019-11-18 22:27:35,322] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor     raise InvalidToken
[2019-11-18 22:27:35,322] {{base_task_runner.py:115}} INFO - Job 38: Subtask file_sensor cryptography.fernet.InvalidToken
[2019-11-18 22:27:37,336] {{logging_mixin.py:95}} INFO - [[34m2019-11-18 22:27:37,335[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 1[0m
